package com.example.draw.rtle.clocksource.model;

import java.io.Serializable;

public class Clock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.serial_no
     *
     * @mbg.generated
     */
    private String serialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.clock_name
     *
     * @mbg.generated
     */
    private String clockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.colock_id
     *
     * @mbg.generated
     */
    private String colockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.x
     *
     * @mbg.generated
     */
    private Float x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.y
     *
     * @mbg.generated
     */
    private Float y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.z
     *
     * @mbg.generated
     */
    private Float z;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.mac
     *
     * @mbg.generated
     */
    private String mac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.online
     *
     * @mbg.generated
     */
    private String online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock.enable
     *
     * @mbg.generated
     */
    private String enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.id
     *
     * @return the value of clock.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.id
     *
     * @param id the value for clock.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.serial_no
     *
     * @return the value of clock.serial_no
     *
     * @mbg.generated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.serial_no
     *
     * @param serialNo the value for clock.serial_no
     *
     * @mbg.generated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.clock_name
     *
     * @return the value of clock.clock_name
     *
     * @mbg.generated
     */
    public String getClockName() {
        return clockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.clock_name
     *
     * @param clockName the value for clock.clock_name
     *
     * @mbg.generated
     */
    public void setClockName(String clockName) {
        this.clockName = clockName == null ? null : clockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.colock_id
     *
     * @return the value of clock.colock_id
     *
     * @mbg.generated
     */
    public String getColockId() {
        return colockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.colock_id
     *
     * @param colockId the value for clock.colock_id
     *
     * @mbg.generated
     */
    public void setColockId(String colockId) {
        this.colockId = colockId == null ? null : colockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.x
     *
     * @return the value of clock.x
     *
     * @mbg.generated
     */
    public Float getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.x
     *
     * @param x the value for clock.x
     *
     * @mbg.generated
     */
    public void setX(Float x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.y
     *
     * @return the value of clock.y
     *
     * @mbg.generated
     */
    public Float getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.y
     *
     * @param y the value for clock.y
     *
     * @mbg.generated
     */
    public void setY(Float y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.z
     *
     * @return the value of clock.z
     *
     * @mbg.generated
     */
    public Float getZ() {
        return z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.z
     *
     * @param z the value for clock.z
     *
     * @mbg.generated
     */
    public void setZ(Float z) {
        this.z = z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.ip
     *
     * @return the value of clock.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.ip
     *
     * @param ip the value for clock.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.mac
     *
     * @return the value of clock.mac
     *
     * @mbg.generated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.mac
     *
     * @param mac the value for clock.mac
     *
     * @mbg.generated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.online
     *
     * @return the value of clock.online
     *
     * @mbg.generated
     */
    public String getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.online
     *
     * @param online the value for clock.online
     *
     * @mbg.generated
     */
    public void setOnline(String online) {
        this.online = online == null ? null : online.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock.enable
     *
     * @return the value of clock.enable
     *
     * @mbg.generated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock.enable
     *
     * @param enable the value for clock.enable
     *
     * @mbg.generated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", serialNo=").append(serialNo);
        sb.append(", clockName=").append(clockName);
        sb.append(", colockId=").append(colockId);
        sb.append(", x=").append(x);
        sb.append(", y=").append(y);
        sb.append(", z=").append(z);
        sb.append(", ip=").append(ip);
        sb.append(", mac=").append(mac);
        sb.append(", online=").append(online);
        sb.append(", enable=").append(enable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}