package com.example.draw.rtle.model;
/** 
* @version 创建时间：2020年6月2日 下午3:09:35
*/
public class Anchor {
	private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.serial_no
     *
     * @mbg.generated
     */
    private String serialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.enable
     *
     * @mbg.generated
     */
    private String enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.anchor_id
     *
     * @mbg.generated
     */
    private String anchorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.anchor_name
     *
     * @mbg.generated
     */
    private String anchorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.x
     *
     * @mbg.generated
     */
    private Float x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.y
     *
     * @mbg.generated
     */
    private Float y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.z
     *
     * @mbg.generated
     */
    private Float z;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anchor.mac
     *
     * @mbg.generated
     */
    private String mac;

    private String online;
    
	public String getOnline() {
		return online;
	}

	public void setOnline(String online) {
		this.online = online;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSerialNo() {
		return serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public String getEnable() {
		return enable;
	}

	public void setEnable(String enable) {
		this.enable = enable;
	}

	public String getAnchorId() {
		return anchorId;
	}

	public void setAnchorId(String anchorId) {
		this.anchorId = anchorId;
	}

	public String getAnchorName() {
		return anchorName;
	}

	public void setAnchorName(String anchorName) {
		this.anchorName = anchorName;
	}

	public Float getX() {
		return x;
	}

	public void setX(Float x) {
		this.x = x;
	}

	public Float getY() {
		return y;
	}

	public void setY(Float y) {
		this.y = y;
	}

	public Float getZ() {
		return z;
	}

	public void setZ(Float z) {
		this.z = z;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getMac() {
		return mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	@Override
	public String toString() {
		return "Anchor [id=" + id + ", serialNo=" + serialNo + ", enable=" + enable + ", anchorId=" + anchorId
				+ ", anchorName=" + anchorName + ", x=" + x + ", y=" + y + ", z=" + z + ", comments=" + comments
				+ ", ip=" + ip + ", mac=" + mac + ", online=" + online + "]";
	}

	
	
    
	
}
